#!/bin/sh
#


prog0=/Library/Internet\ Plug-Ins/NPXMLAPlugin.webplugin/
if test -d "$prog0"
then 
    /bin/rm -fdR "$prog0"
fi

prog=$HOME/Library/Internet\ Plug-Ins/NPXMLAPlugin.webplugin/ 
if test -d "$prog1"
then 
    /bin/rm -fdR "$prog1"
fi

exit 0
